version: "3"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=languages_db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=languages_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:latest

volumes:
  postgres_data:
