version: "3"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:latest

volumes:
  postgres_data:
